// https://www.akc.org/dog-breeds/
const dogChars = {
   'Affenpinscher' : ['Giggly', 'Happy', 'Focused', 'Uplifted'],
   'Afghan Hound': ['Insomnia', 'Euphoric', 'Uplifted', 'Giggly'], 
   'Airedale Terrier': ['Creative', 'Uplifted', 'Energetic', 'Lack of Appetite'], 
   'Akbash': [], 
   'Akita': ['Depression', 'Focused', 'Anxious', 'Relaxed'], 
   'Alaskan Malamute': ['Energetic', 'Talkative', 'Focused'], 
   'American Bulldog': ['Relaxed', 'Hungry', 'Sleepy'], 
   'American Bully': [], 
   'American Eskimo Dog': ['Uplifted', 'Happy', 'Energetic', 'Headaches'], 
   'American Foxhound': ['Relaxed', 'Nausea', 'Euphoric', 'Energetic'],  
   'American Hairless Terrier': ['Energetic', 'Aroused', 'Paranoid', 'Fatigue'], 
   'American Staffordshire Terrier': ['Happy', 'Pain', 'Aroused', 'Energetic'], 
   'American Water Spaniel': ['Euphoric', 'Stress', 'Uplifted', 'Giggly'], 
   'Anatolian Shepherd': ['Depression', 'Relaxed', 'Hungry', 'Creative'], 
   'Appenzell Mountain Dog': [], 
   'Aussiedoodle': [], 
   'Australian Cattle Dog / Blue Heeler': ['Energetic', 'Focused', 'Creative', 'Happy'], 
   'Australian Kelpie': ['Energetic', 'Paranoid', 'Focused', 'Talkative'], 
   'Australian Shepherd': ['Energetic', 'Focused', 'Creative'], 
   'Australian Terrier': ['Euphoric', 'Stress', 'Giggly', 'Tingly'], 
   'Basenji': ['Aroused', 'Lack of Appetite', 'Tingly', 'Energetic'], 
   'Basset Hound': ['Fatigue', 'Sleepy', 'Happy'], 
   'Beagle ': ['Happy', 'Energetic', 'Talkative'], 
   'Bearded Collie': ['Tingly', 'Giggly', 'Cramps', 'Dizzy'], 
   'Beauceron': ['Insomnia', 'Uplifted', 'Anxious', 'Relaxed'], 
   'Bedlington Terrier': ['Euphoric', 'Depression', 'Giggly', 'Dry Eyes'], 
   'Belgian Shepherd / Laekenois': ['Pain', 'Tingly', 'Energetic', 'Focused'], 
   'Belgian Shepherd / Malinois': ['Anxious', 'Energetic', 'Euphoric', 'Focused'], 
   'Belgian Shepherd / Sheepdog': ['Anxious', 'Energetic', 'Hungry', 'Focused'],
   'Belgian Shepherd / Tervuren': ['Anxious', 'Uplifted', 'Hungry', 'Dizzy'],
   'Bernedoodle': [], 
   'Bernese Mountain Dog': ['Stress', 'Muscle Spasms', 'Happy', 'Euphoric'], 
   'Bichon Frise': ['Giggly', 'Euphoric', 'Happy', 'Dry Mouth'], 
   'Black and Tan Coonhound': ['Anxious', 'Energetic', 'Hungry', 'Tingly'], 
   'Black Labrador Retriever': ['Happy', 'Uplifted', 'Euphoric', 'Stress'], 
   'Black Mouth Cur': [], 
   'Black Russian Terrier': ['Focused', 'Relaxed', 'Stress', 'Anxious'], 
   'Bloodhound': ['Energetic', 'Focused', 'Creative', 'Happy'], 
   'Blue Lacy': [], 
   'Bluetick Coonhound': ['Energetic', 'Focused', 'Creative', 'Happy'], 
   'Boerboel': ['Hungry', 'Stress', 'Anxious', 'Relaxed'], 
   'Bolognese': ['Giggly', 'Uplifted', 'Happy', 'Seizures'], 
   'Border Collie': ['Energetic', 'Aroused', 'Focused', 'Euphoric'], 
   'Border Terrier': ['Aroused', 'Eye Pressure', 'Giggly', 'Creative'], 
   'Borzoi': ['Euphoric', 'Creative', 'Depression', ], 
   'Boston Terrier': ['Tingly', 'Giggly', 'Relaxed'], 
   'Bouvier des Flandres': ['Euphoric', 'Paranoid', 'Hungry', 'Dry Eyes'], 
   'Boxer': ['Uplifted', 'Creative', 'Muscle Spasms', 'Energetic'], 
   'Boykin Spaniel': ['Happy', 'Tingly', 'Depression', 'Uplifted'], 
   'Briard': ['Nausea', 'Creative', 'Focused', 'Dizzy'], 
   'Brittany Spaniel': ['Uplifted', 'Tingly', 'Giggly', 'Spasticity'], 
   'Brussels Griffon': ['Depression', 'Focused', 'Paranoid', 'Talkative'], 
   'Bull Terrier': ['Happy', 'Stress', 'Talkative', 'Creative'], 
   'Bullmastiff': ['Paranoid', 'Euphoric', 'Energetic', 'Focused'], 
   'Cairn Terrier': ['Paranoid', 'Happy', 'Giggly', 'Fatigue'], 
   'Canaan Dog': ['Paranoid', 'Uplifted', 'Aroused', 'Inflammation'], 
   'Cane Corso': [], 
   'Cardigan Welsh Corgi': [], 
   'Carolina Dog': ['Happy', 'Creative', 'Energetic', 'Paranoid'], 
   'Catahoula Leopard Dog': ['Happy', 'Creative', 'Energetic'], 
   'Cattle Dog': ['Happy', 'Creative', 'Energetic', 'Focused'], 
   'Caucasian Sheepdog / Caucasian Ovtcharka': [], 
   'Cavachon': [], 
   'Cavalier King Charles Spaniel': ['Anxious', 'Sleepy', 'Aroused', 'Paranoid'], 
   'Cavapoo': [], 
   'Chesapeake Bay Retriever': [], 
   'Chihuahua': ['Talkative', 'Paranoid', 'Energetic', 'Tingly'], 
   'Chinese Crested Dog': ['Euphoric', 'Energetic', 'Giggly', 'Stress'], 
   'Chinese Foo Dog': [], 
   'Chinook': [], 
   'Chiweenie': [], 
   'Chocolate Labrador Retriever': ['Happy', 'Uplifted', 'Euphoric', 'Stress'],
   'Chow Chow': ['Relaxed', 'Hungry', 'Focused', 'Headache'], 
   //'Cirneco dell'Etna': [], 
   'Clumber Spaniel': [], 
   'Cockapoo': [], 
   'Cocker Spaniel': ['Happy', 'Giggly', 'Energetic', 'Insomnia'], 
   'Collie': ['Energetic', 'Aroused', 'Focused', 'Euphoric'],  
   'Coonhound': [], 
   'Corgi': ['Focused', 'Stress', 'Energetic', 'Happy'], 
   'Coton de Tulear': [], 
   'Curly-Coated Retriever': [], 
   'Dachshund': ['Creative', 'Uplifted', 'Giggly', 'Relaxed'], 
   'Dalmatian': ['Euphoric', 'Uplifted', 'Energetic', 'Nausea'], 
   'Dandie Dinmont Terrier': [], 
   'Doberman Pinscher': ['Focused', 'Energetic', 'Giggly', 'Talkative'], 
   'Dogo Argentino': [], 
   'Dogue de Bordeaux': [], 
   'Dutch Shepherd': [], 
   'English Bulldog': ['Relaxed', 'Happy', 'Creative', 'Pain'],  
   'English Cocker Spaniel': ['Relaxed', 'Happy', 'Energetic', 'Paranoid'], 
   'English Coonhound': [], 
   'English Foxhound': ['Relaxed', 'Nausea', 'Euphoric', 'Energetic'],  
   'English Pointer': [], 
   'English Setter': [], 
   'English Shepherd': [], 
   'English Springer Spaniel': [], 
   'English Toy Spaniel': [], 
   'Entlebucher': [], 
   'Eskimo Dog': ['Uplifted', 'Happy', 'Energetic', 'Headaches'], 
   'Feist': [], 
   'Field Spaniel': [], 
   'Fila Brasileiro': [], 
   'Finnish Lapphund': [], 
   'Finnish Spitz': [], 
   'Flat-Coated Retriever': [], 
   'Fox Terrier': ['Stress', 'Focused', 'Aroused', 'Hungry'], 
   'Foxhound': ['Relaxed', 'Nausea', 'Euphoric', 'Energetic'], 
   'French Bulldog': ['Relaxed', 'Happy', 'Creative', 'Pain'], 
   'Galgo Spanish Greyhound': [], 
   'German Pinscher': ['Euphoric', 'Paranoid', 'Energetic', 'Creative'], 
   'German Shepherd Dog': ['Focused', 'Energetic', 'Seizures', 'Euphoric'], 
   'German Shorthaired Pointer': [], 
   'German Spitz': ['Energetic', 'Giggly', 'Aroused', 'Depression'], 
   'German Wirehaired Pointer': [], 
   'Giant Schnauzer': [], 
   'Glen of Imaal Terrier': [], 
   'Golden Retriever': ['Relaxed', 'Happy', 'Giggly'], 
   'Goldendoodle': ['Relaxed', 'Happy', 'Giggly'], 
   'Gordon Setter': [], 
   'Great Dane': ['Relaxed', 'Sleepy', 'Hungry'], 
   'Great Pyrenees': ['Focused', 'Stress', 'Happy', 'Giggly' ], 
   'Greater Swiss Mountain Dog': [], 
   'Greyhound': ['Uplifted', 'Aroused', 'Spasticity', 'Happy' ], 
   'Hamiltonstovare': [], 
   'Harrier': [], 
   'Havanese': ['Giggly', 'Depression', 'Happy', 'Uplifted'], 
   'Hound': ['Happy', 'Creative', 'Energetic', 'Focused'], 
   'Hovawart': [], 
   'Husky': ['Happy', 'Creative', 'Energetic', 'Focused', 'Talkative'], 
   'Ibizan Hound': [], 
   'Icelandic Sheepdog': [], 
   'Illyrian Sheepdog': [], 
   'Irish Setter': [], 
   'Irish Terrier': [], 
   'Irish Water Spaniel': [], 
   'Irish Wolfhound': [], 
   'Italian Greyhound': [], 
   'Jack Russell Terrier': ['Giggly', 'Paranoid', 'Happy', 'Energetic'], 
   'Japanese Chin': [], 
   'Jindo': [], 
   'Kai Dog': [], 
   'Karelian Bear Dog': [], 
   'Keeshond': [], 
   'Kerry Blue Terrier': [], 
   'Kishu': [], 
   'Klee Kai': [], 
   'Komondor': [], 
   'Kuvasz': [], 
   'Kyi Leo': [], 
   'Labradoodle': ['Happy', 'Energetic', 'Talkative', ''], 
   'Labrador Retriever': ['Happy', 'Energetic', 'Talkative', 'Paranoid'], 
   'Lakeland Terrier': [], 
   'Lancashire Heeler': [], 
   'Leonberger': ['Happy', 'Energetic', 'Creative', 'Stress'], 
   'Lhasa Apso': [], 
   'Lowchen': [], 
   'Lurcher': [], 
   'Maltese': ['Sleepy', 'Giggly', 'Tingly'], 
   'Maltipoo': [], 
   'Manchester Terrier': [], 
   'Maremma Sheepdog': [], 
   'Mastiff': ['Paranoid', 'Euphoric', 'Energetic', 'Focused'], 
   'McNab': [], 
   'Miniature Bull Terrier': [], 
   'Miniature Dachshund': [], 
   'Miniature Pinscher': [], 
   'Miniature Poodle': [], 
   'Miniature Schnauzer': [], 
   'Mixed Breed': ['Happy', 'Euphoric', 'Energetic', 'Uplifted'], 
   'Morkie': [], 
   'Mountain Cur': [], 
   'Mountain Dog': [], 
   'Munsterlander': [], 
   'Neapolitan Mastiff': ['Paranoid', 'Euphoric', 'Energetic', 'Focused'], 
   'New Guinea Singing Dog': [], 
   'Newfoundland Dog': [], 
   'Norfolk Terrier': [], 
   'Norwegian Buhund': [], 
   'Norwegian Elkhound': [], 
   'Norwegian Lundehund': [], 
   'Norwich Terrier': [], 
   'Nova Scotia Duck Tolling Retriever': [], 
   'Old English Sheepdog': [], 
   'Otterhound': [], 
   'Papillon': [], 
   'Parson Russell Terrier': [], 
   'Patterdale Terrier / Fell Terrier': [], 
   'Pekingese': [], 
   'Pembroke Welsh Corgi': [], 
   'Peruvian Inca Orchid': [], 
   'Petit Basset Griffon Vendeen': [], 
   'Pharaoh Hound': [], 
   'Pit Bull Terrier': ['Happy', 'Euphoric', 'Energetic', 'Uplifted'], 
   'Plott Hound': [], 
   'Pointer': [], 
   'Polish Lowland Sheepdog': [], 
   'Pomeranian': ['Euphoric', 'Energetic', 'Giggly'], 
   'Pomsky': ['Euphoric', 'Energetic', 'Giggly'], 
   'Poodle': ['Creative', 'Energetic', 'Talkative'], 
   'Portuguese Podengo': [], 
   'Portuguese Water Dog': [], 
   'Presa Canario': [], 
   'Pug': ['Giggly', 'Hungry', 'Sleepy'], 
   'Puggle': ['Giggly', 'Hungry', 'Sleepy'], 
   'Puli': [], 
   'Pumi': [], 
   'Pyrenean Shepherd': [], 
   'Rat Terrier': [], 
   'Redbone Coonhound': [], 
   'Retriever': [], 
   'Rhodesian Ridgeback': [], 
   'Rottweiler': [], 
   'Rough Collie': [], 
   'Saint Bernard': [], 
   'Saluki': [], 
   'Samoyed': [], 
   'Sarplaninac': [], 
   'Schipperke': [], 
   'Schnauzer': [], 
   'Schnoodle': [], 
   'Scottish Deerhound': [], 
   'Scottish Terrier': [], 
   'Sealyham Terrier': [], 
   'Setter': [], 
   'Shar-Pei': [], 
   'Sheep Dog': [], 
   'Sheepadoodle': [], 
   'Shepherd': ['Happy', 'Energetic', 'Paranoid'], 
   'Shetland Sheepdog / Sheltie': [], 
   'Shiba Inu': [], 
   'Shih poo': [], 
   'Shih Tzu': [], 
   'Shollie': [], 
   'Siberian Husky': ['Creative', 'Energetic', 'Talkative', 'Focused'], 
   'Silky Terrier': [], 
   'Skye Terrier': [], 
   'Sloughi': [], 
   'Smooth Collie': [], 
   'Smooth Fox Terrier': [], 
   'South Russian Ovtcharka': [], 
   'Spaniel': [], 
   'Spanish Water Dog': [], 
   'Spinone Italiano': [], 
   'Spitz': [], 
   'Staffordshire Bull Terrier': [], 
   'Standard Poodle': [], 
   'Standard Schnauzer': [], 
   'Sussex Spaniel': [], 
   'Swedish Vallhund': [], 
   'Tennessee Treeing Brindle': [], 
   'Terrier': ['Energetic', 'Uplifted', 'Focused'], 
   'Thai Ridgeback': [], 
   'Tibetan Mastiff': ['Paranoid', 'Euphoric', 'Energetic', 'Focused'], 
   'Tibetan Spaniel': [], 
   'Tibetan Terrier': [], 
   'Tosa Inu': [], 
   'Toy Fox Terrier': [], 
   'Toy Manchester Terrier': [], 
   //'Toyger': [], 
   'Treeing Walker Coonhound': [], 
   'Vizsla': [], 
   'Weimaraner': [], 
   'Welsh Springer Spaniel': [], 
   'Welsh Terrier': ['Relaxed', 'Happy', 'Talkative'], 
   'West Highland White Terrier / Westie': ['Relaxed', 'Happy', 'Talkative'], 
   'Wheaten Terrier': ['Relaxed', 'Happy', 'Talkative'], 
   'Whippet': [], 
   'White German Shepherd': [], 
   'Wire Fox Terrier': [], 
   'Wirehaired Dachshund': [], 
   'Wirehaired Pointing Griffon': [], 
   'Wirehaired Terrier': [], 
   'Xoloitzcuintli / Mexican Hairless': [], 
   'Yellow Labrador Retriever': ['Happy', 'Energetic', 'Talkative', 'Paranoid'], 
   'Yorkshire Terrier': ['Giggly', 'Relaxed', 'Happy'], 
} 
